<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>TechCurse.Api.IntegrationTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Moq" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Api\TechCurse.Api.csproj" />
    <ProjectReference Include="..\..\src\Application\TechCurse.Application.csproj" />
    <ProjectReference Include="..\..\src\Domain\TechCurse.Domain.csproj" />
    <ProjectReference Include="..\..\src\Infrastructure\TechCurse.Infrastructure.csproj" />
  </ItemGroup>

</Project>
