services:
  db:
    ports: !reset []
    deploy:
      resources:
        limits:
          memory: 2G

  redis:
    ports: !reset []
    deploy:
      resources:
        limits:
          memory: 256M

  api:
    image: ${API_IMAGE}
    pull_policy: never
    restart: "no"
