<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>TechCurse.ArchitectureTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NetArchTest.Rules" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Api\TechCurse.Api.csproj" />
    <ProjectReference Include="..\..\src\Application\TechCurse.Application.csproj" />
    <ProjectReference Include="..\..\src\Domain\TechCurse.Domain.csproj" />
    <ProjectReference Include="..\..\src\Infrastructure\TechCurse.Infrastructure.csproj" />
  </ItemGroup>

</Project>
